### ISSUE TITLE
Context menu misplaced

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#14]
Sometimes the context menu is displayed:
![screenshot_2017-04-28_22-48-27](https://cloud.githubusercontent.com/assets/599565/25552013/5152678e-2c65-11e7-9ff0-415b4069dc81.png)

**Comment by alexxcons** [comment]
I cannot reproduce the bug, you only pressed right-mouse on autogen.sh ? 
Possibly the bug is caused by the extended context-menu. I dont have "execute", "Move to Dropbox" and "Create Archive" extensions.

**Comment by andreldm** [comment]
Steps to reproduce:
* Open thunar source folder
* Right click any item on top side
* Right click any item on bottom side

This glitch happens on any view mode, not only Detailed List.
I was able to reproduce on another computer without the mentioned extensions.

**Comment by alexxcons** [comment]
interesting ... does not happen for me.
If I right-click on any top-item, the context menu is fixed to that item. The second right-click on the bottom item for me just closes the open context menu of the top item.

**Comment by andreldm** [comment]
Even using another theme (Adwaita) the problem persists for me:
![screenshot_2017-05-15_18-47-15](https://cloud.githubusercontent.com/assets/599565/26081232/4c554966-39a0-11e7-91cb-4ce3afa5494b.png)

**Comment by andreldm** [comment]
Issue added to Roadmap's Known Issues.

**Comment by alexxcons** [comment]
Finally, by luck, I was able to reproduce this bug. :-)
- It only happens if there are files which have a different number of context menu items in the folder
- it only happens on the lower part of the screen, when the context menu is displayed on top of the mouse
- it only happens if first a "bigger" context menu is opened (e.g. from a folder ) and after that a smaller one is opened (e.g. from a text file )
- it only happens once. If I right click the same file again, the menu-position is correct
- I can confirm that it is a regression. Does not happen for thunar-gtk2

**Comment by alexxcons** [comment]
I tracked the problem down to `gtk_ui_manager_get_widget` inside `thunar_standard_view_context_menu`.

This loads the thunar-standard-view-ui.xml . I tried to replace the loaded menu with my own dummy menu ( different size for files and folders ) , but than the bug does not occur.

Later I saw that the same bug exists as well for nautilus and for nemo --> gtk3 to blame.
However `gtk_ui_manager_get_widget` is deprecated. So possibly this issue is all about replacing the deprecation.
