### ISSUE TITLE
Missing "open terminal here"

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#23]

**Comment by alexxcons** [comment]
looks like the plugin "thunar-uca" is not loaded. At least there is no "edit" --> "Configure Custom Actions", which should be there, according to the thunar-uca README.

In thunar/gtk2 that's the place where "open terminal with" can be enabled / disabled.

**Comment by andreldm** [comment]
I've started porting archive-plugin to check how well we're supporting plugins with thunarx-3:
https://github.com/andreldm/thunar-archive-plugin (oops forgot to push, I'll fix this soon...)

Differently of uca, tpa loads when one tries to use it: "No suitable archive manager found" 😕

**Comment by alexxcons** [comment]
Ok, this one was simple: The problem is, that you need to run `sudo make install` to get uca (and maybe as well other plugins) enabled.
It seems to be safe to do so, without messing the system, since there is as well `sudo make uninstall`.

However there is a problem with `libthunarx-2.so.0`. The installed thunar binary refs `/usr/lib/x86_64-linux-gnu/libthunarx-2.so.0`, which is gtk2.
So it is needed to modify the `LD_LIBRARY_PATH` before start:
`LD_LIBRARY_PATH="/path/to/thunar/thunarx/.libs:/usr/local/lib:$LD_LIBRARY_PATH`
... however this should be fixed with #5 I quess

**Comment by andreldm** [comment]
Yes, indeed. I must be dumb or something, because here at home I uninstalled thunar-gtk2 in favor of gtk3, but I didn't notice that Open Terminal Here was there all the time, probably I was even using it 🙄
Last time I checked this I was at work, so running from the source folder and loading plugins from prefix/lib/thunarx-2 won't work. Thanks!

**Comment by alexxcons** [comment]
Same for #26, can as well be closed
