### ISSUE TITLE
Unremoveable Items in Side Pane

### ISSUE THREAD

**Issue by flocculant** [andreldm/thunar#25]
gtk3 thunar includes the standard /home folders like Music, Pictures etc - these are all unremoveable.

I don't need to see them - I'd like to be able to not see them ;)

**Comment by andreldm** [comment]
I don't have those folders so they don't appear on sidebar even if I recreate them, but I can see them on the screenshots you provided on #27. Funny greybird doesn't use symbolic icons...
This is one of the "advantages" of using GtkPlacesSidebar. In my IMHO its API is rather limited, if it does more harm than good we might consider to switch back to Thunar's old sidebar and try to port it.

For this case, I'll take some time to dig into GtkPlacesSidebar code and check how can we disable this behavior.

**Comment by vc-01** [comment]
+1 Too many unremovable items

@andreldm For me items show up when `startxfce4` was run then thunar (from inside docker container).

Worse is, _xdg_ folders are hardcoded in `GtkPlacesSidebar` and this class is not derivable, so reverting sidebar patch and porting old one to _gtk3_ is probably the only way here.

**Comment by andreldm** [comment]
I was able to recreate these folders following instructions provided [here](https://wiki.archlinux.org/index.php/XDG_user_directories).

@vc-01 You mean [add_special_dirs](https://github.com/GNOME/gtk/blob/4724a89022ef1bec93b1a42d4cf2fec7191ed712/gtk/gtkplacessidebar.c#L577), right?
They are created as PLACES_XDG_DIR, but only PLACES_BOOKMARK items [seem to be removable](https://github.com/GNOME/gtk/blob/4724a89022ef1bec93b1a42d4cf2fec7191ed712/gtk/gtkplacessidebar.c#L2100).

Well, I filed a [bug on gnome bz](https://bugzilla.gnome.org/show_bug.cgi?id=783670), let's hear the devs before jumping back to Thunar's old sidebar.

**Comment by vc-01** [comment]
Maybe jumping to old sidebar will be necessary - I made a revert PR for it.

Other way might be dealing with XDG user dirs somewhere in XFCE global settings by offering option to disable them to the user (outside of Thunar scope). But I haven't looked over it in more detail.

**Comment by andreldm** [comment]
Even though GtkPlacesSidebar is a ready to use component and cuts off 4k lines of code, we'll depend on Gtk folks to make improvements as differences/limitations appear, even if they are fast and/or we contribute with patches, these changes will only be available in subsequent Gtk releases.
I see this change as a risk because we aim an 1:1 port and introducing a different component needs more testing than an existing one. This change could cause even more delays.
I also would like to make it clear that I don't dislike GtkPlacesSidebar 😃, only that it's not going to happen in this porting cycle, maybe in a future release.

So consider this issue fix as we reverted to the old sidebar.
