### ISSUE TITLE
Copying files dialog cancel button missing icon

### ISSUE THREAD

**Issue by andreldm** [andreldm/thunar#44]
![screenshot_2017-08-01_16-44-06](https://user-images.githubusercontent.com/599565/28843863-064dde6c-76d9-11e7-9ef8-deaee8eeb030.png)

**Comment by alexxcons** [comment]
In thunar-progress-view.c the image was removed without replacement by commit 84713ed0e5ff3de0cd432e8584ffbb8ab0df1bf4
CommitMessage: get rid of GTK_STOCK_*

Code to add old icon without using GTK_STOCK:
```
  image = gtk_image_new_from_icon_name ("process-stop", GTK_ICON_SIZE_BUTTON);
  gtk_container_add (GTK_CONTAINER (button), image);
  gtk_widget_show (image); 
```
Or, what I would prefer. Just Write "Cancel" on the button:
```
  button = gtk_button_new_with_label (_("Cancel"));
```
Not sure about translation. _("Cancel") does not give a automatic translation.
_("_Cancel") is translated into "_Abbrechen".

I reviewed the whole commit.. it looks like there are more Images which were removed without replacement.
**thunar-chooser-dialog.c**:580
Tthat's the "file --> open with" dialog.  In gtk2-thunar there was a "process-stop" icon on abort and a "folder" icon on open --> Fine to remove IMO

**thunar-permissions-chooser.c**:404
Right-click --> properties --> permissions. In gtk2-thunar icons on help and close button, not any more for gtk3. Ok for me .. dont have a strong opinion on this one

**thunar-templates-action.c**:494
right click --> new Document --> Empty File. "process-stop" icon on abort button in gtk2/thunar  --> Fine to remove IMO

**thunar-tree-view.c**:1288, 1370 and 1391 1399, 1411 ...
In the thunar/gtk3 tree-view sidebar on right-click no icons are shown any more . To be replaced properly, instead of deletion  IMO

**Comment by andreldm** [comment]
What an extensive analysis!
I don't like the Gnome stance on dropping icons almost everywhere, but that's just a matter of taste. This is not well defined for Xfce, I ask to keep icons where possible with minimal effort otherwise a label shouldn't hurt.

`thunar-chooser-dialog.c:580`
hmmm, I might sound controversial, but I think it's fine without icons

`thunar-permissions-chooser.c:404`
not sure either

`thunar-templates-action.c:494`
I agree to remove, create button had no icon anyway.

`thunar-tree-view.c:1288, 1370 and 1391 1399, 1411 ...`
yep, let's try to restore the icons

**Comment by alexxcons** [comment]
Ok, agreed, done in #47:
- thunar-progress-view.c gets back it's "process-stop" icon.
- thunar-tree-view.c get's back all its icons.
